name: gmpi
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scipy
  - tqdm
  - h5py
  - jupyterlab
  - matplotlib
  - joblib
  - lz4
  - pylint
  - pillow=6.1
  - pytorch=1.9.1
  - torchvision=0.10.1
  - torchaudio==0.9.1
  - cudatoolkit=10.2
  - tensorboard
  - pip
  - pip:
    - setuptools==59.5.0
    - lpips
    - yacs
    - scikit-image
    - scikit-video
    - imageio
    - opencv-python
    - black
    - trimesh
    - flake8
    - flake8-bugbear
    - flake8-comprehensions
    - clean-fid
    - torch_ema
    - torch-fidelity
    - mrcfile
    - dill
    - click
    - psutil
    - lazy
    - imageio-ffmpeg==0.4.3
    - pyspng==0.1.0
    - PyMCubes
